# Generated by Django 4.2.28 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0002_faculty_student_bledetection_phone_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyoffence',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='offence_receipts/faculty/'),
        ),
        migrations.AddField(
            model_name='studentoffence',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='offence_receipts/students/'),
        ),
    ]
