# Generated by Django 4.2.28 on 2026-03-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_app', '0003_facultyoffence_receipt_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
