# Generated by Django 4.2.28 on 2026-03-08 07:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_registration_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=255)),
                ('place_details', models.TextField(blank=True, null=True)),
                ('user_location', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eta_minutes', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student_phone', models.CharField(db_index=True, max_length=20)),
                ('notification_type', models.CharField(choices=[('accepted', 'Driver Accepted'), ('rejected', 'Request Rejected'), ('eta', 'ETA Update'), ('arrived', 'Driver Arrived'), ('in_progress', 'On The Way'), ('completed', 'Booking Completed')], max_length=20)),
                ('message', models.TextField()),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offence_type', models.CharField(choices=[('bus_overspeed', 'Bus Overspeed'), ('student_speed', 'Student Speed Violation')], max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_registration_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.FloatField()),
                ('speed_limit', models.FloatField()),
                ('location', models.JSONField(blank=True, default=dict, null=True)),
                ('rfid_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RFIDDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rfid_id', models.CharField(max_length=100, unique=True)),
                ('location_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('registration_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('dob', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('driver', 'Driver'), ('admin', 'Admin')], default='student', max_length=20)),
                ('driver_type', models.CharField(blank=True, choices=[('bus', 'Bus'), ('ambulance', 'Ambulance'), (None, 'None')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('gps_imei', models.CharField(max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(choices=[('bus', 'Bus'), ('ambulance', 'Ambulance')], max_length=20)),
                ('assigned_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_out_of_station', models.BooleanField(default=False)),
                ('current_location', models.JSONField(blank=True, default=dict, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='core_user_phone_18c349_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='core_user_email_38052c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_id'], name='core_user_registr_d3da51_idx'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='offence',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_offences', to='core.user'),
        ),
        migrations.AddField(
            model_name='offence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_offences', to='core.user'),
        ),
        migrations.AddField(
            model_name='offence',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.booking'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_bookings', to='core.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_active', 'vehicle_type'], name='core_trip_is_acti_ea26c9_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'is_active'], name='core_trip_driver__f4abc7_idx'),
        ),
        migrations.AddIndex(
            model_name='offence',
            index=models.Index(fields=['offence_type', 'is_paid'], name='core_offenc_offence_54ec82_idx'),
        ),
        migrations.AddIndex(
            model_name='offence',
            index=models.Index(fields=['timestamp'], name='core_offenc_timesta_775051_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student_phone', 'created_at'], name='core_notifi_student_1f9be1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['user_role'], name='core_issue_user_ro_9ad245_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='core_issue_status_2609e6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='core_bookin_status_fe12a1_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['phone'], name='core_bookin_phone_1b1199_idx'),
        ),
    ]
