# Generated by Django 4.2.28 on 2026-03-05 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_role', models.CharField(choices=[('student', 'Student'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='core.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user_role'], name='core_issue_user_ro_9ad245_idx'), models.Index(fields=['status'], name='core_issue_status_2609e6_idx')],
            },
        ),
    ]
