# Generated by Django 4.2.28 on 2026-03-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_student_1f9be1_idx',
            old_name='core_notif_student_phone_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='core_notifi_is_read_127eae_idx',
            old_name='core_notif_is_read_idx',
        ),
    ]
