# Generated by Django 4.2.28 on 2026-03-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_notif_student_phone_created_at_idx_core_notifi_student_1f9be1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
